version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm i -g hereya-cli aws-cdk
      - npm install
  pre_build:
    commands:
      - hereya login --token=$HEREYA_TOKEN $HEREYA_CLOUD_URL
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - hereya deploy -w $DEPLOY_WORKSPACE
artifacts:
  files:
    - 'dist/**/*'
